src/routes/admin.php
<?php
/**
 * Created by PhpStorm.
 * User: Александр
 * Date: 09.10.2019
 * Time: 23:35
 */

//Admin routes ,require auth and admin permissions
use App\Http\Middleware\CheckAdminAccess;
use Illuminate\Support\Facades\Route;

Route::get('/admin/{any}', function () {
    return view('layouts.cabinet');
})->where('any', '.*')->middleware(['auth', CheckAdminAccess::class]);

Route::group(['prefix' => 'crud', 'as' => 'crud'], function () {
    Route::group([
        'prefix' => 'admin',
        'namespace' => 'CRUD\Admin',
        'middleware' => ['auth', CheckAdminAccess::class],
    ], function () {
        Route::apiResource('categories', 'CategoryController');
        Route::apiResource('products', 'ProductController');
        Route::apiResource('sales', 'SaleController');
        Route::apiResource('articles', 'ArticleController');
        Route::apiResource('projects', 'ProjectController');
        Route::post('orders/{order}/notify', 'OrderController@notify');
        Route::apiResource('orders', 'OrderController');
        Route::apiResource('promocodes', 'PromocodeController');
        Route::apiResource('companies', 'CompanyController');

        Route::post('order-products/{orderProduct}/layouts',
            'OrderProductController@storeLayouts');
        Route::put('order-products/{orderProduct}/review',
            'OrderProductController@review');
        Route::apiResource('order-products', 'OrderProductController');

        Route::put('order-product-layouts', 'OrderProductLayoutController@updateBulk');
        Route::apiResource('order-product-layouts', 'OrderProductLayoutController');

        Route::put('settings', 'SettingController@update');
        Route::apiResource('settings', 'SettingController');

        Route::get('/users/self', 'UserController@getSelf');
        Route::put('/users/self', 'UserController@updateSelf');
        Route::apiResource('/users', 'UserController');

        Route::apiResource('mailings', 'MailingController')->only(['index', 'store']);

        Route::get('/permissions', 'PermissionController@index');
    });
});

src/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Middleware\CheckAdminAccess;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Redis;

//require_once "redirects.php";

require_once "admin.php";
require_once "base.php";
require_once "client.php";

Route::get('/test', function () {
    dd(phpinfo());
});

src/app/Models/Product.php
<?php
/**
 * Created by PhpStorm.
 * User: Александр
 * Date: 31.05.2019
 * Time: 19:46
 */

namespace App\Models;

use App\Elastic\Product\ProductIndexConfigurator;
use App\Http\RequestedScope;
use ScoutElastic\Searchable;

class Product extends RequestedScope
{
    use Searchable;

    protected $indexConfigurator = ProductIndexConfigurator::class;

    // Here you can specify a mapping for model fields
    protected $mapping = [
        'properties' => [
            'name' => [
                'type' => 'text',
            ],
        ]
    ];

    protected $fillable = ['name', 'seo_name', 'meta_words', 'order_weight', 'description', 'accent', 'disabled',
        'meta_title', 'sales', 'count_calculating', 'h1', 'min_count',
        'base_price', 'base_layout_price', 'base_cost', 'production_time', 'count_name', 'count_type', 'image_id',
        'order_files_extensions', 'order_files_count', 'order_files_extensions', 'order_files_validator_url',
        'count_symbol', 'count_code',
    ];

    protected $availableWith = ['images', 'parameters', 'parameters.values', 'parameters.values.image',
        'projects', 'categories', 'image', 'recommendations', 'mediaFiles'];

    protected $casts = [
        'base_price' => 'double',
        'base_layout_price' => 'double',
        'base_cost' => 'double',
        'sales' => 'array',
        'order_files_extensions' => 'array',
    ];

    protected $appends = ['lowPrice', 'link'];
    protected $with = ['image'];


    public function scopeActive($query)
    {
        return $query->where('disabled', false);
    }

    public function scopeAccented($query)
    {
        return $query->where('accent', true)->where('disabled', false);
    }

    public function getRouteKeyName()
    {
        return 'seo_name';
    }

    public function image()
    {
        return $this->belongsTo(MediaFile::class);
    }

    public function mediaFiles()
    {
        return $this->belongsToMany(MediaFile::class, 'product_media_file');
    }

    public function parameters()
    {
        return $this->hasMany(ProductParameter::class);
    }

    public function articles()
    {
        return $this->belongsToMany(Article::class, 'article_products');
    }

    public function projects()
    {
        return $this->belongsToMany(Project::class, 'product_project')
            ->orderByDesc('created_at');
    }

    public function recommendations()
    {
        return $this->belongsToMany(Product::class, 'product_recommendations',
            'product_id', 'rec_product_id');
    }

    public function getProjectsSet()
    {
        $imgProjects = $this->projects()->inRandomOrder()->whereHas('mediaFile', function ($query) {
            $query->where('type', '!=', 'embed');
        })->take(12)->with('mediaFile')->get();
        $videoProjects = $this->projects()->whereHas('mediaFile', function ($query) {
            $query->where('type', '=', 'embed');
        })->take(6)->with('mediaFile')->get();

        $res = $imgProjects;

        foreach ($videoProjects as $index => $video) {
            $res->splice($index * 6, 0, [$video]);
        }
        return $res->take(12 - $videoProjects->count());
    }

    public function categories()
    {
        return $this->belongsToMany(Category::class, 'products_categories');
    }

    public function mainCategory()
    {
        $category = $this->categories->first();
        if (!$category) {
            $category = Category::all()->first();
        }
        return $category;
    }

    public function getMetaDescriptionAttribute()
    {
        if ($this->meta_words) {
            return $this->meta_words;
        } else {
            return $this->name . ' - рассчитать стоимость и посмотреть оптовые скидки в каталоге услуг.';
        }
    }

    public function getLowPriceAttribute()
    {
        $price = $this->base_price;
        $defaultSalesMap = $this->sales['default'] ?? [];
        if (count($defaultSalesMap) > 0) {
            $price *= 1 - floatval(end($defaultSalesMap)['sale']);
        }
        return round($price, 2);
    }

    public function breadCrumbs()
    {
        $breadcrumbs = $this->mainCategory()->breadCrumbs();

        array_push($breadcrumbs,
            ['name' => $this->name, 'link' => route('products.show', ['product' => $this->seo_name])]);

        return $breadcrumbs;
    }

    public function getLinkAttribute()
    {
        return route('products.show', ['product' => $this->seo_name]);
    }
}

src/resources/views/article.blade.php
@extends('layouts.app')
@push('head')
    @if($article->name)
        <title>{{$article->name}}</title>
    @endif
    <meta name="description"
          content="{{Str::limit(strip_tags($article->text),100)}}">
    <link rel="canonical" href="{{route('articles.show', ['article'=>$article->seo_name])}}"/>
@endpush
@section('content')
    <div class="container mb-5">
        <h1>{{$article->name}}</h1>
        {!! $article->text !!}
    </div>
    <div class="container">
        <div class="mb-5">
            @include('components.slider-recommendations', ['products'=>$sliderProducts])
        </div>
    </div>
    <div class="mb-n5">
        @include('components.slider-sales')
    </div>
@endsection

src/resources/views/categories.blade.php
@extends('layouts.app')
@push('head')
    <title>Каталог услуг типографии и рекламного агентства</title>
    <meta name="description"
          content="Рассчитать стоимость любых видов печати и рекламных услуг с учётом оптовых и индивидуальных скидок.">
@endpush
@section('content')
    <div class="container">
        @include('components.breadcrumbs',['items' => [
            ['name' => 'Главная', 'link' => '/'],
            ['name' => 'Каталог услуг'],
        ]])
        <div class="text-center mb-5">
            <h1>КАТАЛОГ НАШИХ УСЛУГ</h1>
            <div class="h5">ДЛЯ ВАШЕГО БИЗНЕСА</div>
        </div>
        <div class="row">
            @foreach($categories as $category)
                <div class="col-6 col-sm-6 col-md-4 col-lg-3 mb-4">
                    @include('components.card-category', ['category'=>$category])
                </div>
            @endforeach
        </div>
    </div>
@endsection

src/resources/views/category.blade.php
@extends('layouts.app')
@push('head')
    @if($category->meta_title)
        <title>{{$category->meta_title}}</title>
    @else
        <title>{{$category->name}} в Сургуте - заказать онлайн</title>
    @endif
    @if($category->meta_words)
        <meta name="description"
              content="{{$category->meta_words}}">
    @else
        <meta name="description"
              content="{{$category->name}} - рассчитать стоимость с учетом скидок в каталоге услуг.">
    @endif
    <link rel="canonical" href="{{route('categories.show', ['category'=>$category->seo_name])}}"/>
@endpush
@section('content')
    {{--todo keywords--}}
    <div class="container">
        @include('components.breadcrumbs',['items' => $category->breadCrumbs()])
        <div class="text-center mb-5">
            <h1>{{$category->h1??$category->name}}</h1>
        </div>
        <div class="row">
            @foreach($category->children as $child)
                <div class="col-6 col-sm-6 col-md-4 col-lg-3 mb-4">
                    @include('components.card-category', ['category'=>$child])
                </div>
            @endforeach
            @foreach($category->products as $product)
                <div class="col-6 col-sm-6 col-md-4 col-lg-3 mb-4">
                    @include('components.card-product', ['product'=>$product])
                </div>
            @endforeach
        </div>

        <div class="text-justify">
            {!!$category->description!!}
        </div>
    </div>
@endsection

src/resources/views/checkout.blade.php
@extends('layouts.app')
@push('head')
    <title>Оформление заказа</title>
@endpush
@section('content')
    <div class="container">
        <order-checkout
                :delivery-zones="{{json_encode($deliveryZones)}}"
                :free-delivery-from="{{$freeDeliveryFrom}}"
        ></order-checkout>
    </div>
@endsection

src/resources/views/contacts.blade.php
@extends('layouts.app')
@push('head')
    <title>Контакты</title>
    <meta name="description"
          content="📞 Контактная информация рекламного агентства Буква ПЛЮС. Адрес, карта проезда, номера телефонов.">
@endpush
@section('content')
    <div class="container">
        @include('components.breadcrumbs',['items' => [
            ['name' => 'Главная', 'link' => '/'],
            ['name' => 'Контакты'],
        ]])
        <div class="text-center mb-5">
            <i class="icofont-ui-contact-list icofont-3x text-danger"></i>
            <h1>КОНТАКТЫ</h1>
            <div class="h5">
                УЛ. 30 ЛЕТ ПОБЕДЫ, 33А<br/>
                ОФИС 105, 107<br/>
                ТЕЛ.: 8 (3462) 950-250<br/>
                EMAIL: 950250@bk.ru
            </div>
        </div>
        <div class="mb-5">
            <table class="mx-auto">
                <tbody>
                <tr>
                    <td class="text-danger text-right pr-5 py-2">Режим работы офиса:</td>
                    <td class="py-2">По будням с 10<sup>00</sup> до 18<sup>00</sup></td>
                </tr>
                <tr>
                    <td class="text-danger text-right pr-5 py-2">Юридический адрес:</td>
                    <td class="py-2">628403, Тюменская обл., ХМАО-Югра, г. Сургут, ул. 30 лет Победы, 33а</td>
                </tr>
                <tr>
                    <td class="text-danger text-right pr-5 py-2">КПП:</td>
                    <td class="py-2">860201001</td>
                </tr>
                <tr>
                    <td class="text-danger text-right pr-5 py-2" style="vertical-align: top">Банк:</td>
                    <td class="py-2">ЗАПАДНО-СИБИРСКИЙ БАНК<br/>
                        ПАО СБЕРБАНК Г. ТЮМЕНЬ
                    </td>
                </tr>
                <tr>
                    <td class="text-danger text-right pr-5 py-2">Р/с:</td>
                    <td class="py-2">40702810167170000266</td>
                </tr>
                <tr>
                    <td class="text-danger text-right pr-5 py-2">К/с:</td>
                    <td class="py-2">30101810800000000651</td>
                </tr>
                <tr>
                    <td class="text-danger text-right pr-5 py-2">БИК:</td>
                    <td class="py-2">047102651</td>
                </tr>
                <tr>
                    <td class="text-danger text-right pr-5 py-2" style="vertical-align: top">Генеральный директор:</td>
                    <td class="py-2">Чернов Павел Анатольевич<br/>
                        Действует на основании устава.
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    @include('components.map')
@endsection

src/resources/views/delivery.blade.php
@extends('layouts.app')
@push('head')
    <title>Бесплатная доставка полиграфии по Сургуту</title>
    <meta name="description"
          content="🏎 Бесплатную доставка продукции типографии в черте города. Мы рады помочь в экономии вашего времени!">
@endpush
@section('content')
    <div class="container">
        @include('components.breadcrumbs',['items' => [
            ['name' => 'Главная', 'link' => '/'],
            ['name' => 'Доставка'],
        ]])
        <div class="text-center">
            <i class="icofont-fast-delivery icofont-3x text-danger"></i>
            <h1>ДОСТАВКА</h1>
        </div>
        <div class="row text-justify align-items-center">
            <div class="col-12 col-md-6">
                <img src="/images/delivery-surgut.png">
            </div>
            <div class="col-12 col-md-6">
                <p>
                    <strong>Доставка по городу Сургуту</strong> для негабаритной* продукции производится
                    <strong class="text-danger">в соответствии с зоной доставки</strong> в рабочие часы с 10:00 до 20:00.
                    Бесплатная доставка оформляется при заказе от {{$freeDeliveryFrom}} рублей.
                </p>
                <p>
                    <span class="font-weight-bold">*Обращаем Ваше внимание</span>: бесплатно доставляются заказы,
                    размером до 1 метра по каждой
                    из сторон.
                </p>
                <p>
                    В случае, если приемка продукции выполняется третьим лицом (по просьбе заказчика) необходим документ
                    удостоверяющий личность (паспорт, водительское удостоверение). Передача осуществляется при
                    подписании
                    акта/товарной накладной.
                </p>
            </div>
        </div>
        <div class="row text-justify align-items-center mb-4">
            <div class="col-12 col-md-6">
                <p>
                    <strong>Доставка по России</strong> производится транспортными компаниями на выбор заказчика за счет
                    получателя в
                    формате “дверь-дверь”. Вместе с продукцией передаются оригиналы документов.
                </p>
                <p>
                    Мы гарантируем качество продукции, соблюдение сроков исполнения заказа и передачу его в транспортную
                    компанию. В случае, если транспортная компания потеряет печатный тираж, мы перепечатаем и доставим
                    его Вам бесплатно.
                </p>
            </div>
            <div class="col-12 col-md-6">
                <img src="/images/delivery-russia.png">
            </div>
        </div>
        <div class="text-justify mb-5">
            <p>
                <span class="text-danger">*</span> Если Вы оформили заказ через сайт, и указали доставку, то Ваш заказ
                доставят к Вам или в транспортную
                компанию в течение тех сроков, которые были указаны в заказе.
            </p>
            <p>
                <span class="text-danger">**</span> Если Вы оформили заказ через менеджера, то Ваш заказ доставят в
                течение тех сроков, которые Вам
                сообщит
                Ваш персональный менеджер.
            </p>
            <p>
                <span class="text-danger">***</span> Доставка заказа по Сургуту осуществляется непосредственно в Ваш
                офис.
            </p>
            <p>
                <span class="text-danger">****</span> Мы не отгружаем заказы в транспортные компании и не доставляем
                заказы
                в пункты выдачи по выходным и
                праздничным дням.
            </p>
        </div>
    </div>
    @include('components.delivery-map')
@endsection

src/resources/views/payment.blade.php
@extends('layouts.app')
@push('head')
    <title>Оплата изделий</title>
    <meta name="description"
          content="Любые виды оплаты - это про нас! Вы можете оплатить услуги безналичным платежом, банковской картой или наличными средствами.">
@endpush
@section('content')
    <div class="container">
        @include('components.breadcrumbs',['items' => [
            ['name' => 'Главная', 'link' => '/'],
            ['name' => 'Оплата'],
        ]])
        <div class="text-center mb-5">
            <i class="icofont-wallet icofont-3x text-danger"></i>
            <h1>СПОСОБЫ ОПЛАТЫ</h1>
        </div>
        <div class="row text-center">
            <div class="col-12 col-lg-4 mb-5 mb-lg-0 payment-type">
                <i class="icofont-bank-alt"></i>
                <h3 class="text-uppercase">Безналичный расчёт</h3>
                <div class="h5">Для юридических лиц и ИП</div>
            </div>
            <div class="col-12 col-lg-4 mb-5 mb-lg-0 payment-type">
                <i class="icofont-credit-card"></i>
                <h3 class="text-uppercase">Банковской картой</h3>
                <div class="h5">Для физических лиц</div>
            </div>
            <div class="col-12 col-lg-4 payment-type">
                <img src="/images/sberbank.svg">
                <h3 class="text-uppercase">По квитанции в Сбербанке</h3>
                <div class="h5">Для физических лиц</div>
            </div>
        </div>
        <hr class="my-5">
        <div class="row">
            <div class="col-12 col-md-6 mb-3 mb-md-0 text-justify" style="text-indent: 2rem">
                <p>
                    Обращаем Ваше внимание, что мы приступаем к изготовлению заказа после поступления денежных средств
                    на наш расчетный счет.
                </p>
                <p>
                    Для юридических лиц и индивидуальных предпринимателей мы предлагаем услугу постановки заказа в
                    работу,
                    не дожидаясь поступления оплаты. При наличии договора на оказание услуг.
                </p>
            </div>
            <div class="col-12 col-md-6">
                <table class="ml-md-5">
                    <tbody>
                    <tr>
                        <td class="text-danger pr-5">ИНН:</td>
                        <td>8602256565</td>
                    </tr>
                    <tr>
                        <td class="text-danger">КПП:</td>
                        <td>860201001</td>
                    </tr>
                    <tr>
                        <td class="text-danger" style="vertical-align: top">Банк:</td>
                        <td>ЗАПАДНО-СИБИРСКИЙ БАНК<br/>
                            ПАО СБЕРБАНК Г. ТЮМЕНЬ
                        </td>
                    </tr>
                    <tr>
                        <td class="text-danger">Р/с:</td>
                        <td>40702810167170000266</td>
                    </tr>
                    <tr>
                        <td class="text-danger">К/с:</td>
                        <td>30101810800000000651</td>
                    </tr>
                    <tr>
                        <td class="text-danger">БИК:</td>
                        <td>047102651</td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

src/resources/views/product.blade.php
@extends('layouts.app')
@push('head')
    @if($product->meta_title)
        <title>{{$product->meta_title}}</title>
    @else
        <title>{{$product->name}} - Заказать в Сургуте быстро, качественно, недорого</title>
    @endif
    <meta name="description" content="{{$product->meta_description}}">
    <link rel="canonical" href="{{route('products.show', ['product'=>$product->seo_name])}}"/>
@endpush
@section('content')
    <div class="p-product">
        <div class="container">
            @include('components.breadcrumbs',['items' => $product->breadCrumbs()])
            <div itemscope itemtype="http://schema.org/Product">
                <base-calculator class="mb-5"
                                 :product="{{ $calculator_data }}"
                                 :rating="{{ $average_rating }}"
                                 :reviews-count="{{ count($reviews) }}"
                >
                    <div itemprop="name" class="d-none">
                        {{$product->name}}
                    </div>
                    <h1 class="text-uppercase mb-4">{{$product->h1? $product->h1:$product->name}}</h1>
                    <div class="row mb-5 mt-0">
                        <div class="col-12 col-md-4 pr-5">
                            <div class="mb-3">
                                @if($product->image)
                                    <a class="chocolat-image"
                                       itemprop="image"
                                       title="{{ $product->name }}"
                                       href="{{ $product->image->url }}">
                                        <img class="product-image"
                                             title="{{ $product->name }}"
                                             alt="{{ $product->name }}"
                                             src="{{ $product->image->thumbnail }}">
                                    </a>
                                @else
                                    <div class="product-image">
                                        <i class="icofont-image"></i>
                                    </div>
                                @endif
                                @if($average_rating)
                                    <div itemprop="aggregateRating"
                                         itemscope
                                         itemtype="http://schema.org/AggregateRating">
                                        <div class="rating rating_inline">
                                            @for($i=0; $i<5; $i++)
                                                <i class="icofont-star {{ $i <= $average_rating ? 'active' : '' }}"></i>
                                            @endfor
                                            <div itemprop="ratingValue">{{ $average_rating }}</div>
                                            <meta itemprop="bestRating" content="5"/>
                                            <meta itemprop="worstRating" content="1"/>
                                        </div>
                                        <a class="small ml-3" href="#reviews">
                                            Читать отзывы
                                            (<span itemprop="reviewCount">{{ count($reviews) }}</span>)</a>
                                    </div>
                                @endif
                            </div>
                            <div class="position-relative" itemtype="http://schema.org/AggregateOffer" itemscope=""
                                 itemprop="offers">
                                <link itemprop="availability" href="http://schema.org/InStock"/>
                                <meta itemprop="priceCurrency" content="RUB"/>
                                <meta itemprop="lowPrice" content="{{$product->low_price}}"/>
                                <div>
                                    <span class="font-weight-bold">Время изготовления:</span>
                                    {{$product->production_time}}
                                </div>
                                <div class="mb-3">
                                    <span class="font-weight-bold">Цена:</span>
                                    от {{$product->base_price}} ₽ за {{$product->count_type}}
                                </div>
                                <div>
                                    <button class="btn btn-primary" disabled>
                                        <i class="icofont icofont-cart-alt"></i>
                                        Купить
                                    </button>
                                </div>
                            </div>
                        </div>
                        <div class="col-12 col-md-8">
                            @foreach($product->parameters as $index=>$parameter)
                                <div class="mb-4">
                                    <div class="h5 mb-3">
                                        <span class="h1 mr-2">{{$index+1}}.</span>
                                        Выберите <span class="text-lowercase">{{$parameter->name}}</span>
                                    </div>
                                    <div class="btn-group btn-group_sm btn-group_light" role="group">
                                        @foreach($parameter->values as $value)
                                            <button type="button" class="btn">{{$value->name}}</button>
                                        @endforeach
                                    </div>
                                </div>
                            @endforeach
                        </div>
                    </div>
                </base-calculator>
                @if($product->recommendations->count() > 0)
                    <div class="mb-5">
                        @include('components.slider-recommendations', ['products'=>$product->recommendations])
                    </div>
                @endif
                <div class="text-justify product-description mb-5" itemprop="description">
                    <div class="mb-5">{!!$product->description!!}</div>
                    <div class="d-flex justify-content-end">
                        <div class="mr-3">Поделись с друзьями:</div>
                        <div class="list-unstyled ya-share2"
                             data-description="{{$product->meta_description}}"
                             data-image="{{asset($product->image->thumbnail ?? null)}}"
                             data-services="vkontakte,facebook,odnoklassniki,twitter"></div>
                    </div>
                </div>
                @if(count($reviews))
                    <a id="reviews"></a>
                    @include('components.reviews-slider', ['class' => 'mb-5'])
                @endif
                @if($product->projects->count() > 0)
                    <div class="mb-5">
                        <div class="h3 text-uppercase mb-4">Выполненные проекты</div>
                        <div class="row">
                            @foreach($product->getProjectsSet() as $project)
                                @include('components.card-project', ['project'=>$project])
                            @endforeach
                        </div>
                    </div>
                @endif
            </div>
        </div>
    </div>
    @include('components.slider-articles', ['articles'=>$product->articles])
@endsection

src/resources/views/sales.blade.php
@extends('layouts.app')
@push('head')
    <title>Акции, скидки и политика начисления бонусов | Буква ПЛЮС</title>
    <meta name="description"
          content="Оптовые скидки и бонусная программа являются неотъемлемой частью нашего рекламного агентства.">
@endpush
@section('content')
    <div class="container">
        @include('components.breadcrumbs',['items' => [
            ['name' => 'Главная', 'link' => '/'],
            ['name' => 'Акции и скидки'],
        ]])
        <div class="mb-5 text-center">
            <i class="icofont-sale-discount icofont-3x text-danger"></i>
            <h1>НАШИ СКИДКИ</h1>
            <h2 class="h5">И БОНУСНАЯ СИСТЕМА</h2>
        </div>
    </div>
    <div class="container pb-6">
        <h3>
            Бонусная система РА Буква ПЛЮС
        </h3>
        <p>Наша бонусная система позволяет накапливать баллы в размере {{ $bonusBet }}% от суммы заказа, при оформлении онлайн заказа
            с использованием зарегистрированной учетной записи.</p>
        <ul>
            <li>
                Накопленные бонусные баллы за каждую позицию заказа активируется через 14 дней после оформления
                заказа, при условии, что позиция не находится в статусе «Новый», «Ждёт оплаты», «На проверке».
            </li>
            <li>
                Активированные бонусные баллы можно использовать в новых заказах для получения скидки до 100%. Один
                бонусный балл равен одному рублю.
            </li>
            <li>
                Зарегистрированный пользователь в любой момент может посмотреть свою история накопления и
                использования бонусных баллов в личном кабинете.
            </li>
        </ul>

        <p>РА Буква ПЛЮС имеет право отказать пользователю в накоплении и использовании бонусных баллов в следующих
            случаях:</p>
        <ul>
            <li>при оформлении заказа не была использована зарегистрированная учетная запись;</li>
            <li>при оформлении заказа пользователь не указал, что использует бонусные баллы;</li>
            <li>бонусная программа была отменена организатором;</li>
            <li>в случае сбоя кассовой системы и веб сервисов или попытки мошеннических действий с целью получить больше
                бонусных баллов или использовать недействительные бонусные баллы.
            </li>
        </ul>
        <p>
            Организатор оставляет за собой право отменить или изменить всю бонусную систему или ее часть в любое
            время, с предварительным уведомлением об этом. Сообщение об отмене или изменении бонусной системы размещается на
            официальном сайте организатора.
        </p>
    </div>
    @foreach(\App\Models\Sale::active()->get() as $sale)
        <div style="background-image: url({{$sale->mediaFile->url}})" class="sale mb-4">
            <div class="container">
                <div class="row">
                    <div class="col-12 col-md-6">
                        <div class="h1">{{$sale->name}}</div>
                        <div>{!!$sale->description!!}</div>
                    </div>
                </div>
            </div>
        </div>
    @endforeach
@endsection